<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>beancount</string>
		</array>
		<key>name</key>
		<string>Beancount</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>name</key>
				<string>meta.directive.beancount.notetotext</string>
				<key>comment</key>
				<string>Note as Oneliner Transaction directive</string>
				<key>begin</key>
				<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s+(note)(?=(.*\*\"\s))</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.date.year.beancount</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.separator.beancount</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.date.month.beancount</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>punctuation.separator.beancount</string>
					</dict>
					<key>5</key>
					<dict>
						<key>name</key>
						<string>constant.numeric.date.day.beancount</string>
					</dict>
					<key>6</key>
					<dict>
						<key>name</key>
						<string>support.function.directive.beancount</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=(^\s*$|^\S))</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>text.beancount#meta</string>
					</dict>
					<dict>
						<key>include</key>
						<string>text.beancount#comments</string>
					</dict>
					<dict>
						<key>include</key>
						<string>text.beancount#account</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.directive.arguments.beancount.notetotext</string>
						<key>match</key>
						<string>(?&lt;=\s)(\")(.*?)(\s+\*\s+)((.*?)(\s\|\s))?(.*?)(\*\")</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.arguments.begin.beancount.notetotext</string>
							</dict>
							<key>2</key>
							<dict>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>text.beancount#account</string>
									</dict>
									<dict>
										<key>include</key>
										<string>text.beancount#amount</string>
									</dict>
									<dict>
										<key>include</key>
										<string>text.beancount#cost</string>
									</dict>
									<dict>
										<key>include</key>
										<string>text.beancount#illegal</string>
									</dict>
								</array>
							</dict>
							<key>3</key>
							<dict>
								<key>comment</key>
								<string>*</string>
								<key>name</key>
								<string>punctuation.separator.arguments.beancount.notetotext</string>
							</dict>
							<key>5</key>
							<dict>
								<key>comment</key>
								<string>$payee</string>
								<key>name</key>
								<string>constant.other.payee.beancount.notetotext</string>
							</dict>
							<key>6</key>
							<dict>
								<key>comment</key>
								<string>|</string>
								<key>name</key>
								<string>punctuation.separator.arguments.beancount.notetotext</string>
							</dict>
							<key>7</key>
							<dict>
								<key>name</key>
								<string>string.unquoted.beancount.notetotext</string>
								<key>patterns</key>
								<array>
									<dict>
										<key>include</key>
										<string>text.beancount#tag</string>
									</dict>
									<dict>
										<key>include</key>
										<string>text.beancount#link</string>
									</dict>
								</array>
							</dict>
							<key>8</key>
							<dict>
								<key>comment</key>
								<string>*"</string>
								<key>name</key>
								<string>punctuation.definition.arguments.end.beancount.notetotext</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>include</key>
						<string>text.beancount#illegal</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>include</key>
				<string>text.beancount</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>text.beancount.oneline</string>
		<key>uuid</key>
		<string>b1baaa60-7e34-4b20-9898-7f67059267c4</string>
	</dict>
</plist>