<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>beancount</string>
	</array>
	<key>name</key>
	<string>Beancount</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.beancount</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(poptag|pushtag)\s+(#)([A-Za-z0-9\-_/.]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tag.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tag directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.tag.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(include)\s+(\".*\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Include directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.include.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(option)\s+(\".*\")\s+(\".*\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Option directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.option.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(plugin)\s*("(.*?)")\s*(".*?")?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Plugin directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>keyword.operator.directive.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s+(open|close|pad)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Open/Close/Pad directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s+(custom)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Custom directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bool</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(event)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Event directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(commodity)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Commodity directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(note|document)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Note/Document directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s+(query)\s+("(?:[^"\\]|\\.)*")\s+(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Query directive (BQL)</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.beancount</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.query.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]{4}-[0-9]{2}-[0-9]{2}\b</string>
					<key>name</key>
					<string>constant.numeric.date.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:SELECT|FROM|WHERE|GROUP|ORDER|HAVING|LIMIT|PIVOT|AND|OR|NOT|IN|IS|BETWEEN|AS|DISTINCT|ASC|DESC|TRUE|FALSE|NULL|CREATE|TABLE|USING|INSERT|INTO|BALANCES|JOURNAL|PRINT|BY)\b</string>
					<key>name</key>
					<string>keyword.control.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:abs|bool|int|decimal|str|date|year|month|day|yearmonth|quarter|weekday|today|root|parent|leaf|grep|grepn|subst|upper|lower|maxwidth|substr|splitcomp|length|repr|round|safediv|neg|open_date|close_date|open_meta|meta|entry_meta|any_meta|currency_meta|commodity_meta|account_sortkey|has_account|units|cost|value|getprice|number|currency|commodity|findfirst|joinstr|only|empty|filter_currency|convert|parse_date|date_diff|date_add|date_trunc|date_part|interval|date_bin|getitem|possign|sum|count|first|last|min|max)\b(?=\s*\()</string>
					<key>name</key>
					<string>support.function.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:id|type|filename|lineno|location|date|year|month|day|flag|payee|narration|description|tags|links|meta|accounts|account|other_accounts|posting_flag|number|currency|cost_number|cost_currency|cost_date|cost_label|position|price|weight|balance|entry)\b</string>
					<key>name</key>
					<string>variable.other.column.bql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.bql</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>""</string>
							<key>name</key>
							<string>constant.character.escape.bql</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.bql</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>''</string>
							<key>name</key>
							<string>constant.character.escape.bql</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+(\.\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;=|&gt;=|!=|&lt;|&gt;|=|\?~|!~|~</string>
					<key>name</key>
					<string>keyword.operator.comparison.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[+\-*/%]</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.bql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[(),]</string>
					<key>name</key>
					<string>punctuation.bql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(price)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Price directives</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(balance)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Balance directives</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s*(txn|[*!&amp;#?%PSTCURM])\s*(".*?")?\s*(".*?")?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>support.function.directive.txn.completed.beancount</string>
							<key>match</key>
							<string>txn|[*]</string>
						</dict>
						<dict>
							<key>name</key>
							<string>support.function.directive.txn.incomplete.beancount</string>
							<key>match</key>
							<string>!</string>
						</dict>
						<dict>
							<key>name</key>
							<string>support.function.directive.txn.padding.beancount</string>
							<key>match</key>
							<string>P</string>
						</dict>
					</array>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.tiers.beancount</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.quoted.narration.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Transaction directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.transaction.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#posting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>account</key>
		<dict>
			<key>begin</key>
			<string>([A-Z][a-z]+)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>meta.account.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\S+)([:]?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.account.beancount</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.beancount</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Sub accounts</string>
					<key>end</key>
					<string>([:]?)|(\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>bool</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.language.bool.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.currency.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.commodity.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>TRUE|FALSE</string>
		</dict>
		<key>number</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.currency.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\-|\+]?)(\d+(?:,\d{3})*(?:\.\d*)?)</string>
		</dict>
		<key>amount</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.currency.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.commodity.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\-|\+]?)(\d+(?:,\d{3})*(?:\.\d*)?)\s*([A-Z][A-Z0-9\'\.\_\-]{0,22}[A-Z0-9])</string>
			<key>name</key>
			<string>meta.amount.beancount</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;.*)$</string>
		</dict>
		<key>commodity</key>
		<dict>
			<key>match</key>
			<string>([A-Z][A-Z0-9\'\.\_\-]{0,22}[A-Z0-9])</string>
			<key>name</key>
			<string>entity.name.type.commodity.beancount</string>
		</dict>
		<key>cost</key>
		<dict>
			<key>begin</key>
			<string>\{\{?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\}?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.beancount</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.cost.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>date</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})</string>
			<key>name</key>
			<string>meta.date.beancount</string>
		</dict>
		<key>flag</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)([*!&amp;#?%PSTCURM])(?=\s+)</string>
			<key>name</key>
			<string>keyword.other.beancount</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.beancount</string>
		</dict>
		<key>link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.link.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\^)([A-Za-z0-9\-_/.]+)</string>
		</dict>
		<key>meta</key>
		<dict>
			<key>begin</key>
			<string>^\s*([a-z][A-Za-z0-9\-_]+)([:])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.directive.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.meta.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bool</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>posting</key>
		<dict>
			<key>begin</key>
			<string>^\s+(?=([A-Z\!]))</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S|^\s*[A-Z]))</string>
			<key>name</key>
			<string>meta.posting.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cost</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#price</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>price</key>
		<dict>
			<key>begin</key>
			<string>\@\@?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(;|\n))</string>
			<key>name</key>
			<string>meta.price.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.beancount</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tag.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)([A-Za-z0-9\-_/.]+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.beancount</string>
	<key>uuid</key>
	<string>dbf28879-ee4d-497e-a678-a5c5a5e8d74f</string>
</dict>
</plist>