<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>beancount</string>
	</array>
	<key>name</key>
	<string>Beancount</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.beancount</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(poptag|pushtag)\s+(#)([A-Za-z0-9\-_/.]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tag.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tag directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.tag.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(include)\s+(\".*\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Include directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.include.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(option)\s+(\".*\")\s+(\".*\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Option directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.option.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(plugin)\s*("(.*?)")\s*(".*?")?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Plugin directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>keyword.operator.directive.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s+(open|close|pad|custom)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Open/Close/Pad directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(event)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Event directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(commodity)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Commodity directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(note|document)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Note/Document directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(price)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Price directives</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s(balance)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Balance directives</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.dated.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})\s*(txn|[*!&amp;#?%PSTCURM])\s*(".*?")?\s*(".*?")?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.directive.beancount</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.quoted.tiers.beancount</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.quoted.narration.beancount</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Transaction directive</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S))</string>
			<key>name</key>
			<string>meta.directive.transaction.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#posting</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>account</key>
		<dict>
			<key>begin</key>
			<string>([A-Z][a-z]+)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>meta.account.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\S+)([:]?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.account.beancount</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.beancount</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Sub accounts</string>
					<key>end</key>
					<string>([:]?)|(\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>bool</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.language.bool.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.currency.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.type.commodity.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>TRUE|FALSE</string>
		</dict>
		<key>number</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.currency.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\-|\+]?)(\d+(?:,\d{3})*(?:\.\d*)?)</string>
		</dict>
		<key>amount</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.currency.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.type.commodity.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\-|\+]?)(\d+(?:,\d{3})*(?:\.\d*)?)\s*([A-Z][A-Z0-9\'\.\_\-]{0,22}[A-Z0-9])</string>
			<key>name</key>
			<string>meta.amount.beancount</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;.*)$</string>
		</dict>
		<key>commodity</key>
		<dict>
			<key>match</key>
			<string>([A-Z][A-Z0-9\'\.\_\-]{0,22}[A-Z0-9])</string>
			<key>name</key>
			<string>entity.type.commodity.beancount</string>
		</dict>
		<key>cost</key>
		<dict>
			<key>begin</key>
			<string>\{\{?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\}?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.beancount</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.cost.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>date</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.year.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.month.beancount</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.date.day.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9]{4})([\-|/])([0-9]{2})([\-|/])([0-9]{2})</string>
			<key>name</key>
			<string>meta.date.beancount</string>
		</dict>
		<key>flag</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)([*!&amp;#?%PSTCURM])(?=\s+)</string>
			<key>name</key>
			<string>keyword.other.beancount</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>[^\s]</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.beancount</string>
		</dict>
		<key>link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.link.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\^)([A-Za-z0-9\-_/.]+)</string>
		</dict>
		<key>meta</key>
		<dict>
			<key>begin</key>
			<string>^\s*([a-z][A-Za-z0-9\-_]+)([:])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.directive.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.meta.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bool</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commodity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>posting</key>
		<dict>
			<key>begin</key>
			<string>^\s+(?=([A-Z\!]))</string>
			<key>end</key>
			<string>(?=(^\s*$|^\S|^\s*[A-Z]))</string>
			<key>name</key>
			<string>meta.posting.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#account</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cost</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#price</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>price</key>
		<dict>
			<key>begin</key>
			<string>\@\@?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.beancount</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(;|\n))</string>
			<key>name</key>
			<string>meta.price.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#amount</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.beancount</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.beancount</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tag.beancount</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.beancount</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)([A-Za-z0-9\-_/.]+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.beancount</string>
	<key>uuid</key>
	<string>dbf28879-ee4d-497e-a678-a5c5a5e8d74f</string>
</dict>
</plist>
